### ISSUE TITLE
How to run instructions are unclear

### ISSUE THREAD

**Issue by del-cj** [cis3296s23/project-01-drpg#18]
There were a few things I noticed in your instruction set that were confusing. First, I was unsure which files to open and which to move. Another confusion I had was in the technical information part. During the setup of the bot, it was not listed which permissions the bot should have, just a warning not to give it Admin permissions. I am unsure what permissions the bot will need as I did not write it or look at its code. If I didn't know what I was doing, I could see myself accidentally not giving the bot enough permissions.

**Comment by peter-shoes** [comment]
Documentation has been updated accordingly.
