### ISSUE TITLE
My Experience trying to test the bot

### ISSUE THREAD

**Issue by princegeutler** [cis3296s23/project-01-drpg#19]
I was able to get the discord bot onto my server for DungeonRPG, however the readme file did not account for people not having python or even pip installed. I had to figure out how to do it myself and then also install the required extra packages (i.e Pillow) to run the actual code (which was also no included in the readme). Then when I got the discord bot onto my server I was unable to actually use it since there is no guidance on the commands to use to start the game. I was using Mac OS. Please let me know if perhaps I missed something.

**Comment by peter-shoes** [comment]
We assume contributors will have basic knowledge of python and pip, this is otherwise outside the domain of our project. We were actually missing the pillow install, added that in the latest update.
Guidance on bot setup has been updated in the readme.
